langauge: python

matrix:
   include:
      - os: linux
        sudo: required
        python: 2.7
        env: TOXENV=py27
      - os: linux
        sudo: required
        python: 3.3
        env: TOXENV=py33

install:
 - pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
 - pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
 - pip install -U scikit-learn
 - pip install .
 - pip install nose coverage
 - pip install coveralls
script:
 - python setup.py nosetests --with-coverage

after_success:
 -  coveralls


