langauge: python

python:
 - "2.7.14"
 - "3.3"

install:
 - pip install --user --upgrade https://github.com/Theano/Theano/archive/master.zip
 - pip install --user --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
 - travis_wait pip install --user .
 - travis_wait pip install --user nose coverage
 - pip install --user coveralls

script:
 - python setup.py nosetests --with-coverage

after_success:
 - coveralls


